### ISSUE TITLE
devices timeout issue

### ISSUE THREAD

**Issue by cganoe** [dart4e/dart4e#29]
This extension works great for the most part, so thanks, but I keep getting errors when it's checking for devices. I looked at the code, and it looks like it's waiting for 5 seconds, and when I run "flutter devices" from the command line (Mac), it's taking around 5 seconds. So, I keep guessing the extension is timing out before it can get info on the devices available. Is there anything that can be done about this? 
![image](https://github.com/dart4e/dart4e/assets/30124444/388d8c1a-45bf-4d01-8fc5-c80a1093fe73)

**Comment by sebthom** [comment]
Please check if you can gather a complete stacktrace, e.g. have a look at the `<your_workspace_folder>\.metadata\.log` file

**Comment by cganoe** [comment]
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (org.apache.commons.io.input.CharSequenceInputStream); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:360)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2095)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
	at org.dart4e.util.io.JSON.deserializeList(JSON.java:103)
	at org.dart4e.flutter.model.FlutterSDK$1.run(FlutterSDK.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by sebthom** [comment]
I increased the wait timeout to 10 seconds. Please check if it helps.

**Comment by cganoe** [comment]
Thanks! Yes, that helps.
