### ISSUE TITLE
NPE when trying to add a new Flutter SDK

### ISSUE THREAD

**Issue by bensler** [dart4e/dart4e#38]
I successfully added a new Dart SDK (3.5.2) and then tried adding a Flutter SDK. After selecting the folder I extracted the flutter TAR into, nothing happened, but e new entry appeared in the Error Log view:
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of 

"java.io.BufferedReader.readLine()" is null
	at org.dart4e.flutter.model.FlutterSDK.lambda$2(FlutterSDK.java:102)
	at net.sf.jstuff.core.functional.Suppliers$2.get(Suppliers.java:85)
	at org.dart4e.flutter.model.FlutterSDK.isValid(FlutterSDK.java:253)
	at org.dart4e.flutter.prefs.FlutterSDKEditDialog.onBrowseForSDKButton(FlutterSDKEditDialog.java:179)
	at de.sebthom.eclipse.commons.ui.Buttons$2.widgetSelected(Buttons.java:55)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.dart4e.flutter.prefs.FlutterSDKPreferencePage.onButton_Add(FlutterSDKPreferencePage.java:196)
	at de.sebthom.eclipse.commons.ui.Buttons$2.widgetSelected(Buttons.java:55)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5854)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5064)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:648)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)

eclipse.buildId=4.30.0.20231201-1200
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -data file:/home/thomas/Documents/dev/workspace/2023-12/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

I tried debugging it myself, but I did not get dart4e Plugin running in debug mode (I am a Java developer but never did any Eclipse plugin development). I am using Ubuntu, maybe some things behave differently on that platform. I am willing to help, if you let me know how.

**Comment by bensler** [comment]
Framework • revision 67457e669f (7 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

**Comment by bensler** [comment]
it is the stable flutter_linux_3.16.8-stable.tar.xz I downloaded from https://docs.flutter.dev/release/archive?tab=linux

**Comment by sebthom** [comment]
The code is looking for a line starting with "Flutter" to determine the flutter version, something like this:
```
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (5 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```
It's odd that it is missing from your output.

**Comment by sebthom** [comment]
Can you try `flutter doctor --version` ?

**Comment by bensler** [comment]
> It's odd that it is missing from your output.

Uh, sorry, my fault. Missed the first line when c&p'ing. Output is:

Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (7 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

> Can you try flutter doctor --version?

exactly the same output as above

**Comment by sebthom** [comment]
ok, I don't use linux for desktop development. so I need your help to pin this down. 

1) when you run `flutter --version` is the output send to stdout or stderr?
2) can you execute run `flutter --version` directly using `java.lang.ProcessBuilder or do you need to use something like `/bin/sh -c "flutter --version"`?

**Comment by bensler** [comment]
> 1. when you run flutter --version is the output send to stdout or stderr?

`./bin/flutter --version > out.txt 2> err.txt`

results are in these two files:

`-rw-rw-r--  1 thomas thomas  226 Jan 23 16:00 out.txt`
`-rw-rw-r--  1 thomas thomas    0 Jan 23 16:00 err.txt`

which means, it came out on stdout

> 2. can you execute run flutter --version directly using java.lang.ProcessBuilder or do you need to use something like /bin/sh -c "flutter --version"`?

```
public static void main(String[] args) throws IOException {
  final Process process = new ProcessBuilder("/opt/flutter/3.16.8/bin/flutter", "--version").start();

  try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
    String line;
    while ((line = reader.readLine()) != null) {
      System.out.println(line);
    }
  }
}
```

... reproduced exactly the same output as calling `flutter --version` directly in a shell. No abnormal behavior so far :-/

**Comment by sebthom** [comment]
Could you try running it using this ProcessBuilder wrapper: https://github.com/sebthom/jstuff/blob/main/jstuff-core/src/main/java/net/sf/jstuff/core/io/Processes.java  Maybe there is a bug.

```xml
  <dependencies>
    <dependency>
      <groupId>net.sf.jstuff</groupId>
      <artifactId>jstuff-core</artifactId>
      <version>7.6.0</version>
    </dependency>
  </dependencies>
```
```java
final var processBuilder = Processes.builder(flutterExe).withArg("--version");
try (var reader = new BufferedReader(new InputStreamReader(processBuilder.start().getStdOut()))) {
  String line;
  while ((line = reader.readLine()) != null) {
    System.out.println(line);
  }
}
```

**Comment by bensler** [comment]
> Could you try running it using this ProcessBuilder wrapper ...

gives exactly the expected output:

```
Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (7 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5
```

(I replaced `flutterExe` with `"/opt/flutter/3.16.8/bin/flutter"`)

**Comment by sebthom** [comment]
I now added a check for null. This will avoid the NPE but probably won't solve the actual issue you are facing. But maybe give it a try and see what happens.

**Comment by bensler** [comment]
well ... it did the trick! I did not expect that neither ;)

Btw, awesome support and great collaborative experience!
