### ISSUE TITLE
Debug doesn't work

### ISSUE THREAD

**Issue by Kaban77** [dart4e/dart4e#61]
I run my "hello world" application in debug mode, progress bar stuck at 73%
![ScreenShot](https://github.com/user-attachments/assets/1d3264ce-8b91-485a-8458-90c0a3161409)

`eclipse.buildId=4.33.0.20240905-0613
java.version=21.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product`

These logs appear after forced termination of the application. There are no other logs

`!ENTRY org.dart4e 4 4 2024-10-28 11:32:10.648
!MESSAGE Cancelled
!STACK 1
org.eclipse.debug.core.DebugException: Cancelled
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugElement.monitorGet(DSPDebugElement.java:99)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.initialize(DSPDebugTarget.java:220)
	at org.dart4e.launch.LaunchDebugConfig.createDebugTarget(LaunchDebugConfig.java:118)
	at org.dart4e.launch.LaunchDebugConfig.createDebugTarget(LaunchDebugConfig.java:1)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:384)
	at org.dart4e.launch.program.ProgramLaunchConfigLauncher.launch(ProgramLaunchConfigLauncher.java:98)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugElement.monitorGet(DSPDebugElement.java:84)
	... 10 more
!SUBENTRY 1 org.eclipse.lsp4e.debug 8 5010 2024-10-28 11:32:10.649
!MESSAGE Cancelled
!STACK 0
java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugElement.monitorGet(DSPDebugElement.java:84)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.initialize(DSPDebugTarget.java:220)
	at org.dart4e.launch.LaunchDebugConfig.createDebugTarget(LaunchDebugConfig.java:118)
	at org.dart4e.launch.LaunchDebugConfig.createDebugTarget(LaunchDebugConfig.java:1)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.launch(DSPLaunchDelegate.java:384)
	at org.dart4e.launch.program.ProgramLaunchConfigLauncher.launch(ProgramLaunchConfigLauncher.java:98)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by sebthom** [comment]
I cant reproduce. Debugging works fine for me. Please provide a complete example.

**Comment by Kaban77** [comment]
Dart sdk version is 3.5.4
